{% set name = "w3lib" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c8ac02a3027576174c2b61eb9a2170ba1b197cae767080771b6f1febda249a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - w3lib

    - w3lib.html
    - w3lib.http
    - w3lib.url

about:
  home: https://github.com/scrapy/w3lib/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This is a Python library of web-related functions

  description: |
    This is a Python library of web-related functions, such as
    remove comments, or tags from HTML snippets,
    extract base url from HTML snippets,
    translate entites on HTML strings,
    convert raw HTTP headers to dicts and vice-versa,
    construct HTTP auth header,
    converting HTML pages to unicode,
    sanitize urls (like browsers do),
    extract arguments from urls.
  dev_url: https://github.com/scrapy/w3lib

extra:
  recipe-maintainers:
    - astrojuanlu
