{% set name = "w3lib" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed5b74e997eea2abe3c1321f916e344144ee8e9072a6f33463ee8e57f858a4b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six

test:
  imports:
    - w3lib

    - w3lib.html
    - w3lib.http
    - w3lib.url

about:
  home: https://github.com/scrapy/w3lib/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This is a Python library of web-related functions

  description: |
    This is a Python library of web-related functions, such as
    remove comments, or tags from HTML snippets,
    extract base url from HTML snippets,
    translate entites on HTML strings,
    convert raw HTTP headers to dicts and vice-versa,
    construct HTTP auth header,
    converting HTML pages to unicode,
    sanitize urls (like browsers do),
    extract arguments from urls.
  dev_url: https://github.com/scrapy/w3lib

extra:
  recipe-maintainers:
    - astrojuanlu
